-- MySQL Script generated by MySQL Workbench
-- Thu May 19 05:28:49 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema consumidor
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema consumidor
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `consumidor` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `consumidor` ;

-- -----------------------------------------------------
-- Table `consumidor`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consumidor`.`clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `consumidor`.`supermercados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consumidor`.`supermercados` (
  `idsupermercado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idsupermercado`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `consumidor`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consumidor`.`comentarios` (
  `idcomentarios` INT NOT NULL AUTO_INCREMENT,
  `clienteid` INT NOT NULL,
  `supermercadoid` INT NOT NULL,
  `calificacion` INT NOT NULL,
  `comentario` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idcomentarios`),
  INDEX `clienteid_comentario_idx` (`clienteid` ASC) VISIBLE,
  INDEX `superid_comentario_idx` (`supermercadoid` ASC) VISIBLE,
  CONSTRAINT `clienteid_comentario`
    FOREIGN KEY (`clienteid`)
    REFERENCES `consumidor`.`clientes` (`id`),
  CONSTRAINT `superid_comentario`
    FOREIGN KEY (`supermercadoid`)
    REFERENCES `consumidor`.`supermercados` (`idsupermercado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `consumidor`.`listasupermercado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consumidor`.`listasupermercado` (
  `idlistasupermercado` INT NOT NULL AUTO_INCREMENT,
  `clienteid` INT NOT NULL,
  `total` FLOAT NOT NULL,
  PRIMARY KEY (`idlistasupermercado`),
  INDEX `id_idx` (`clienteid` ASC) VISIBLE,
  CONSTRAINT `idcliente_lista`
    FOREIGN KEY (`clienteid`)
    REFERENCES `consumidor`.`clientes` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `consumidor`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consumidor`.`productos` (
  `idproducto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `disponible` TINYINT NOT NULL,
  `supermercado` INT NOT NULL,
  `precio` FLOAT NOT NULL,
  `cantidad` INT NOT NULL,
  `categorias` BLOB NULL DEFAULT NULL,
  PRIMARY KEY (`idproducto`),
  INDEX `idsupermercado_idx` (`supermercado` ASC) VISIBLE,
  CONSTRAINT `idsupermercado`
    FOREIGN KEY (`supermercado`)
    REFERENCES `consumidor`.`supermercados` (`idsupermercado`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `consumidor`.`detalleslista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consumidor`.`detalleslista` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `listaid` INT NOT NULL,
  `productoid` INT NOT NULL,
  `cantidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `lista_detalle_idx` (`listaid` ASC) VISIBLE,
  INDEX `producto_detalle_idx` (`productoid` ASC) VISIBLE,
  CONSTRAINT `lista_detalle`
    FOREIGN KEY (`listaid`)
    REFERENCES `consumidor`.`listasupermercado` (`idlistasupermercado`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `producto_detalle`
    FOREIGN KEY (`productoid`)
    REFERENCES `consumidor`.`productos` (`idproducto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `consumidor`.`inconsistencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consumidor`.`inconsistencias` (
  `idinconsistencia` INT NOT NULL AUTO_INCREMENT,
  `clienteid` INT NOT NULL,
  `supermercadoid` INT NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idinconsistencia`),
  INDEX `cliente_inconsistencia_idx` (`clienteid` ASC) VISIBLE,
  INDEX `cliente_supermercado_idx` (`supermercadoid` ASC) VISIBLE,
  CONSTRAINT `cliente_inconsistencia`
    FOREIGN KEY (`clienteid`)
    REFERENCES `consumidor`.`clientes` (`id`),
  CONSTRAINT `cliente_supermercado`
    FOREIGN KEY (`supermercadoid`)
    REFERENCES `consumidor`.`supermercados` (`idsupermercado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `consumidor`.`wishlists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consumidor`.`wishlists` (
  `idwishlist` INT NOT NULL AUTO_INCREMENT,
  `clienteid` INT NOT NULL,
  `productoid` INT NOT NULL,
  PRIMARY KEY (`idwishlist`),
  INDEX `id_idx` (`clienteid` ASC) VISIBLE,
  INDEX `productoid_idx` (`productoid` ASC) VISIBLE,
  CONSTRAINT `id`
    FOREIGN KEY (`clienteid`)
    REFERENCES `consumidor`.`clientes` (`id`),
  CONSTRAINT `productoid`
    FOREIGN KEY (`productoid`)
    REFERENCES `consumidor`.`productos` (`idproducto`))
ENGINE = InnoDB
AUTO_INCREMENT = 32
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
